/**
 * Seeder: Tạo dữ liệu mẫu cho DB
 * Chạy: npm run seed
 * Xóa sản phẩm: npm run seed -- --destroy
 */
require('dotenv').config();
const connectDB = require('../config/db');
const Product = require('../models/Product');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const img = (seed, w = 600, h = 800) => `https://picsum.photos/seed/${seed}/${w}/${h}`;
const sizes = (list) => list;
const variants = (sizeList, colors) =>
  sizeList.flatMap((size) =>
    colors.map(({ color, hex, skuCode }) => ({
      size,
      color,
      colorHex: hex,
      sku: `BOBO-${skuCode}-${size}`.toUpperCase(),
      stock: Math.floor(Math.random() * 60) + 10,
    }))
  );

const CARE = ['Giặt tay hoặc máy ≤ 30°C', 'Không dùng máy sấy', 'Ủi nhiệt độ thấp'];

// ---------------------------------------------------------------------------
// Palette shortcuts
// ---------------------------------------------------------------------------
const RED    = { color: 'Đỏ Racing',   hex: '#C8102E', skuCode: 'RED' };
const BLACK  = { color: 'Đen',         hex: '#1A1A1A', skuCode: 'BLK' };
const WHITE  = { color: 'Trắng',       hex: '#FFFFFF', skuCode: 'WHT' };
const NAVY   = { color: 'Navy',        hex: '#0A1931', skuCode: 'NVY' };
const SILVER = { color: 'Bạc',         hex: '#C0C0C0', skuCode: 'SLV' };
const ORANGE = { color: 'Cam McLaren', hex: '#FF8000', skuCode: 'ORG' };
const BLUE   = { color: 'Xanh Mercedes', hex: '#00D2BE', skuCode: 'BLU' };
const YELLOW = { color: 'Vàng Renault', hex: '#FFF500', skuCode: 'YLW' };
const GREEN  = { color: 'Xanh Aston',  hex: '#006F62', skuCode: 'GRN' };
const PINK   = { color: 'Hồng Pastel', hex: '#FFB6C1', skuCode: 'PNK' };
const CREAM  = { color: 'Kem',         hex: '#FFFDD0', skuCode: 'CRM' };
const GRAY   = { color: 'Xám',         hex: '#808080', skuCode: 'GRY' };
const KHAKI  = { color: 'Khaki',       hex: '#C3B091', skuCode: 'KHK' };
const CARBON = { color: 'Carbon',      hex: '#2E2E2E', skuCode: 'CBN' };

const STD = sizes(['S', 'M', 'L', 'XL']);
const FULL = sizes(['XS', 'S', 'M', 'L', 'XL', 'XXL']);
const OS = sizes(['ONE SIZE']);

// ---------------------------------------------------------------------------
// 100 Products — F1 / Motorsport fashion aesthetic
// ---------------------------------------------------------------------------
const sampleProducts = [

  // =========================================================================
  // ÁO (1–35)
  // =========================================================================
  {
    name: 'Áo Polo BoBo Racing Team - Đỏ Ferrari',
    slug: 'ao-polo-bobo-racing-team-do-ferrari',
    description: 'Áo polo kỹ thuật lấy cảm hứng từ đồng phục đội đua Ferrari. Chất liệu pique co giãn, cổ bẻ cứng cáp, logo BoBo thêu nổi ngực trái.',
    shortDescription: 'Pique co giãn | Cổ bẻ | Thêu logo',
    images: [img('f1-polo-red-1'), img('f1-polo-red-2')],
    category: 'ao', subCategory: 'ao-polo',
    tags: ['new-arrival', 'f1', 'racing', 'best-seller'],
    basePrice: 399000, material: 'Pique Cotton 60%, Polyester 40%',
    careInstructions: CARE,
    variants: variants(STD, [RED, BLACK, WHITE]),
    rating: { average: 4.8, count: 312 }, soldCount: 1540, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Polo BoBo Paddock - Xanh Mercedes',
    slug: 'ao-polo-bobo-paddock-xanh-mercedes',
    description: 'Phong cách paddock Mercedes AMG. Vải pique nhẹ, thoáng mát, phù hợp mặc quanh năm.',
    shortDescription: 'Paddock style | Pique nhẹ | Thoáng mát',
    images: [img('f1-polo-blue-1'), img('f1-polo-blue-2')],
    category: 'ao', subCategory: 'ao-polo',
    tags: ['f1', 'racing', 'new-arrival'],
    basePrice: 399000, material: 'Pique Cotton 60%, Polyester 40%',
    careInstructions: CARE,
    variants: variants(STD, [BLUE, BLACK, NAVY]),
    rating: { average: 4.7, count: 198 }, soldCount: 870, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Polo BoBo Podium - Cam McLaren',
    slug: 'ao-polo-bobo-podium-cam-mclaren',
    description: 'Tone cam đặc trưng McLaren, form slim fit, tay ngắn. Chất liệu cao cấp chống nhăn.',
    shortDescription: 'McLaren Orange | Slim fit | Chống nhăn',
    images: [img('f1-polo-orange-1'), img('f1-polo-orange-2')],
    category: 'ao', subCategory: 'ao-polo',
    tags: ['f1', 'racing'],
    basePrice: 399000, salePrice: 349000, discountPercent: 13,
    material: 'Pique Cotton 60%, Polyester 40%',
    careInstructions: CARE,
    variants: variants(STD, [ORANGE, BLACK, WHITE]),
    rating: { average: 4.6, count: 145 }, soldCount: 620, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Thun BoBo DryFit Kỹ Thuật',
    slug: 'ao-thun-bobo-dryfit-ky-thuat',
    description: 'Vải DryFit thoát hơi nhanh, co giãn 4 chiều. Phù hợp lái xe, tập gym hoặc mặc hàng ngày.',
    shortDescription: 'DryFit | Co giãn 4 chiều | Thoát hơi',
    images: [img('dryfit-tshirt-1'), img('dryfit-tshirt-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['new-arrival', 'technical', 'sport'],
    basePrice: 299000, material: 'Polyester 88%, Spandex 12%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, WHITE, NAVY, CARBON]),
    rating: { average: 4.9, count: 520 }, soldCount: 2300, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Thun BoBo F1 Graphic - Vintage Race',
    slug: 'ao-thun-bobo-f1-graphic-vintage-race',
    description: 'Áo thun in hình đường đua vintage, cotton 100% thoáng mát, wash nhẹ aged look.',
    shortDescription: 'In đường đua | Cotton 100% | Aged look',
    images: [img('graphic-tee-race-1'), img('graphic-tee-race-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['new-arrival', 'graphic', 'vintage', 'f1'],
    basePrice: 349000, material: 'Cotton 100%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, WHITE, GRAY]),
    rating: { average: 4.8, count: 287 }, soldCount: 1100, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Checkered Flag',
    slug: 'ao-thun-bobo-checkered-flag',
    description: 'Họa tiết cờ ca rô đặc trưng đường đua, form oversized, chất cotton nặng 240gsm.',
    shortDescription: 'Họa tiết cờ ca rô | Oversized | 240gsm',
    images: [img('checkered-tee-1'), img('checkered-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'graphic', 'oversized'],
    basePrice: 329000, material: 'Cotton 100% 240gsm',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, WHITE, NAVY]),
    rating: { average: 4.7, count: 201 }, soldCount: 780, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Sơ Mi BoBo Paddock Linen',
    slug: 'ao-so-mi-bobo-paddock-linen',
    description: 'Sơ mi linen cao cấp tone tối giản, phong cách paddock casual. Nhẹ, thoáng, không nhăn.',
    shortDescription: 'Linen cao cấp | Paddock casual | Không nhăn',
    images: [img('linen-shirt-paddock-1'), img('linen-shirt-paddock-2')],
    category: 'ao', subCategory: 'ao-so-mi',
    tags: ['casual', 'premium', 'paddock'],
    basePrice: 499000, material: 'Linen 55%, Cotton 45%',
    careInstructions: CARE,
    variants: variants(STD, [WHITE, CREAM, NAVY]),
    rating: { average: 4.6, count: 134 }, soldCount: 490, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Sơ Mi BoBo Racing Stripe',
    slug: 'ao-so-mi-bobo-racing-stripe',
    description: 'Sơ mi kẻ sọc đua kiểu dáng retro, cổ button-down, phối jeans hoặc chino đều chuẩn.',
    shortDescription: 'Kẻ sọc retro | Button-down | Phối đa dạng',
    images: [img('stripe-shirt-racing-1'), img('stripe-shirt-racing-2')],
    category: 'ao', subCategory: 'ao-so-mi',
    tags: ['retro', 'racing', 'casual'],
    basePrice: 459000, material: 'Cotton Oxford 100%',
    careInstructions: CARE,
    variants: variants(STD, [WHITE, BLUE, RED]),
    rating: { average: 4.5, count: 98 }, soldCount: 310, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Hoodie BoBo Pit Lane',
    slug: 'ao-hoodie-bobo-pit-lane',
    description: 'Hoodie form regular, lót bông giữ ấm, in chữ "PIT LANE" phản quang sau lưng. Chuẩn phong cách garage.',
    shortDescription: 'Phản quang | Lót bông | Garage style',
    images: [img('hoodie-pitlane-1'), img('hoodie-pitlane-2')],
    category: 'ao', subCategory: 'ao-hoodie',
    tags: ['f1', 'streetwear', 'new-arrival'],
    basePrice: 599000, material: 'Cotton 80%, Polyester 20%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, NAVY, CARBON]),
    rating: { average: 4.9, count: 445 }, soldCount: 1980, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Hoodie BoBo Circuit Map',
    slug: 'ao-hoodie-bobo-circuit-map',
    description: 'Hoodie in bản đồ đường đua nổi tiếng thế giới, form oversized trendy.',
    shortDescription: 'In bản đồ đường đua | Oversized | Trendy',
    images: [img('hoodie-circuit-1'), img('hoodie-circuit-2')],
    category: 'ao', subCategory: 'ao-hoodie',
    tags: ['f1', 'graphic', 'oversized'],
    basePrice: 549000, salePrice: 479000, discountPercent: 13,
    material: 'Cotton 80%, Polyester 20%',
    careInstructions: CARE,
    variants: variants(FULL, [GRAY, BLACK, NAVY]),
    rating: { average: 4.7, count: 267 }, soldCount: 930, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Bomber BoBo Racing Heritage',
    slug: 'ao-bomber-bobo-racing-heritage',
    description: 'Bomber jacket vải nylon chống gió nhẹ, lining satin, patches thêu đường đua. Biểu tượng của phong cách racing heritage.',
    shortDescription: 'Nylon chống gió | Satin lining | Racing patches',
    images: [img('bomber-racing-1'), img('bomber-racing-2')],
    category: 'outerwear', subCategory: 'bomber',
    tags: ['f1', 'racing', 'premium', 'new-arrival'],
    basePrice: 1290000, material: 'Nylon 100%, Lining Satin',
    careInstructions: ['Giặt khô', 'Không giặt máy'],
    variants: variants(STD, [BLACK, NAVY, RED]),
    rating: { average: 4.9, count: 189 }, soldCount: 540, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Bomber BoBo Monaco GP',
    slug: 'ao-bomber-bobo-monaco-gp',
    description: 'Bomber giới hạn lấy cảm hứng từ GP Monaco, màu navy sang trọng với chỉ đỏ.',
    shortDescription: 'Limited Monaco | Navy + Chỉ đỏ | Cao cấp',
    images: [img('bomber-monaco-1'), img('bomber-monaco-2')],
    category: 'outerwear', subCategory: 'bomber',
    tags: ['f1', 'limited', 'premium'],
    basePrice: 1490000, material: 'Nylon 100%, Lining Polyester',
    careInstructions: ['Giặt khô'],
    variants: variants(STD, [NAVY, BLACK]),
    rating: { average: 4.8, count: 78 }, soldCount: 220, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Track Jacket BoBo Motorsport',
    slug: 'ao-track-jacket-bobo-motorsport',
    description: 'Track jacket zip toàn thân, bo tay và bo gấu, side stripe dọc. Phong cách vintage motorsport.',
    shortDescription: 'Zip toàn thân | Side stripe | Vintage moto',
    images: [img('track-jacket-1'), img('track-jacket-2')],
    category: 'outerwear', subCategory: 'track-jacket',
    tags: ['f1', 'retro', 'racing', 'new-arrival'],
    basePrice: 799000, material: 'Polyester 100%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, RED, BLUE]),
    rating: { average: 4.7, count: 223 }, soldCount: 890, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Track Jacket BoBo Yellow Renault',
    slug: 'ao-track-jacket-bobo-yellow-renault',
    description: 'Màu vàng rực rỡ đặc trưng Renault, cổ đứng, tay raglan, chất liệu windbreaker.',
    shortDescription: 'Renault Yellow | Tay raglan | Windbreaker',
    images: [img('track-jacket-yellow-1'), img('track-jacket-yellow-2')],
    category: 'outerwear', subCategory: 'track-jacket',
    tags: ['f1', 'racing', 'bright'],
    basePrice: 749000, material: 'Polyester Windbreaker 100%',
    careInstructions: CARE,
    variants: variants(STD, [YELLOW, BLACK]),
    rating: { average: 4.5, count: 112 }, soldCount: 340, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Windbreaker BoBo Circuit',
    slug: 'ao-windbreaker-bobo-circuit',
    description: 'Windbreaker siêu nhẹ có thể gấp gọn thành túi. Chống nước nhẹ, phản quang logo bên hông.',
    shortDescription: 'Siêu nhẹ gấp gọn | Chống nước nhẹ | Phản quang',
    images: [img('windbreaker-circuit-1'), img('windbreaker-circuit-2')],
    category: 'outerwear', subCategory: 'windbreaker',
    tags: ['technical', 'racing', 'new-arrival'],
    basePrice: 899000, material: 'Nylon Ripstop 100%',
    careInstructions: ['Giặt tay nhẹ', 'Không dùng máy sấy'],
    variants: variants(STD, [BLACK, NAVY, RED, ORANGE]),
    rating: { average: 4.8, count: 301 }, soldCount: 1120, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Turtleneck BoBo Podium',
    slug: 'ao-turtleneck-bobo-podium',
    description: 'Turtleneck slim fit phong cách F1 driver chụp ảnh podium. Vải rib cotton giữ form tốt.',
    shortDescription: 'Slim fit | Rib cotton | Podium style',
    images: [img('turtleneck-podium-1'), img('turtleneck-podium-2')],
    category: 'ao', subCategory: 'ao-co-lua',
    tags: ['f1', 'elegant', 'new-arrival'],
    basePrice: 449000, material: 'Cotton Rib 95%, Spandex 5%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, WHITE, NAVY, RED]),
    rating: { average: 4.7, count: 167 }, soldCount: 610, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Turtleneck BoBo Silver Carbon',
    slug: 'ao-turtleneck-bobo-silver-carbon',
    description: 'Màu bạc ánh kim gợi liên tưởng đến vỏ xe Silver Arrow, chất rib mềm mại.',
    shortDescription: 'Silver Arrow tone | Rib mềm | Thanh lịch',
    images: [img('turtleneck-silver-1'), img('turtleneck-silver-2')],
    category: 'ao', subCategory: 'ao-co-lua',
    tags: ['f1', 'premium', 'silver'],
    basePrice: 449000, material: 'Cotton Rib 95%, Spandex 5%',
    careInstructions: CARE,
    variants: variants(STD, [SILVER, BLACK]),
    rating: { average: 4.6, count: 89 }, soldCount: 280, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Phao BoBo Paddock Winter',
    slug: 'ao-phao-bobo-paddock-winter',
    description: 'Áo phao lông vũ nhân tạo siêu nhẹ, form padded vest, phong cách paddock mùa đông.',
    shortDescription: 'Lông vũ nhân tạo | Siêu nhẹ | Paddock winter',
    images: [img('vest-paddock-1'), img('vest-paddock-2')],
    category: 'outerwear', subCategory: 'ao-phao',
    tags: ['winter', 'racing', 'premium'],
    basePrice: 1190000, material: 'Nylon 100%, Fill: Polyester',
    careInstructions: ['Giặt máy nhẹ', 'Không giặt khô'],
    variants: variants(STD, [BLACK, NAVY, RED]),
    rating: { average: 4.8, count: 134 }, soldCount: 450, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Len BoBo Grid Walk',
    slug: 'ao-len-bobo-grid-walk',
    description: 'Áo len dệt kim mỏng, hoạ tiết số xe đua subtle. Phong cách Grid Walk sang trọng.',
    shortDescription: 'Dệt kim mỏng | Hoạ tiết số xe | Grid Walk',
    images: [img('knit-gridwalk-1'), img('knit-gridwalk-2')],
    category: 'ao', subCategory: 'ao-len',
    tags: ['f1', 'elegant', 'knit'],
    basePrice: 699000, material: 'Merino Wool 50%, Acrylic 50%',
    careInstructions: ['Giặt tay nước lạnh', 'Phơi phẳng'],
    variants: variants(STD, [NAVY, CREAM, BLACK]),
    rating: { average: 4.7, count: 145 }, soldCount: 390, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Croptop BoBo Pit Girl',
    slug: 'ao-croptop-bobo-pit-girl',
    description: 'Croptop co giãn in hoạ tiết số vòng đua, form bó nhẹ, chuẩn pit girl aesthetic.',
    shortDescription: 'Co giãn | In số vòng đua | Pit girl',
    images: [img('croptop-racing-1'), img('croptop-racing-2')],
    category: 'ao', subCategory: 'ao-croptop',
    tags: ['f1', 'women', 'trending', 'new-arrival'],
    basePrice: 299000, material: 'Spandex 30%, Cotton 70%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, WHITE, RED]),
    rating: { average: 4.9, count: 378 }, soldCount: 1560, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Carbon Fiber Print',
    slug: 'ao-thun-bobo-carbon-fiber-print',
    description: 'In hoạ tiết carbon fiber full body siêu thực. Vải cotton mềm mịn premium 200gsm.',
    shortDescription: 'Carbon fiber print | Cotton 200gsm | Siêu thực',
    images: [img('carbon-print-tee-1'), img('carbon-print-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'graphic', 'premium'],
    basePrice: 379000, material: 'Cotton 100% 200gsm',
    careInstructions: CARE,
    variants: variants(FULL, [CARBON, BLACK]),
    rating: { average: 4.6, count: 189 }, soldCount: 670, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Podium Champagne',
    slug: 'ao-thun-bobo-podium-champagne',
    description: 'In hình miệng chai champagne vỡ với chữ "P1". Ăn mừng theo phong cách F1.',
    shortDescription: 'P1 Podium print | Ăn mừng F1 | Cotton mềm',
    images: [img('champagne-tee-1'), img('champagne-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'graphic', 'fun'],
    basePrice: 329000, material: 'Cotton 100%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, WHITE, NAVY]),
    rating: { average: 4.8, count: 312 }, soldCount: 1340, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Sơ Mi BoBo Racing Mechanic',
    slug: 'ao-so-mi-bobo-racing-mechanic',
    description: 'Sơ mi kiểu dáng mechanic jacket, túi hộp ngực, bo tay và bo thân chắc chắn.',
    shortDescription: 'Mechanic jacket style | Túi hộp | Chắc chắn',
    images: [img('mechanic-shirt-1'), img('mechanic-shirt-2')],
    category: 'ao', subCategory: 'ao-so-mi',
    tags: ['f1', 'workwear', 'racing'],
    basePrice: 549000, material: 'Cotton Ripstop 100%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, NAVY, RED]),
    rating: { average: 4.7, count: 156 }, soldCount: 510, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Polo BoBo Aston Martin Green',
    slug: 'ao-polo-bobo-aston-martin-green',
    description: 'Xanh Aston Martin Racing lịch lãm, cổ polo 3-button, fit slim tôn vóc dáng.',
    shortDescription: 'Aston Martin Racing | Slim fit | Lịch lãm',
    images: [img('polo-green-aston-1'), img('polo-green-aston-2')],
    category: 'ao', subCategory: 'ao-polo',
    tags: ['f1', 'racing', 'premium'],
    basePrice: 419000, material: 'Pique Cotton 60%, Polyester 40%',
    careInstructions: CARE,
    variants: variants(STD, [GREEN, BLACK, WHITE]),
    rating: { average: 4.6, count: 121 }, soldCount: 420, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Hoodie BoBo Speed Racer',
    slug: 'ao-hoodie-bobo-speed-racer',
    description: 'Hoodie zip full kẻ sọc dọc bên hông vintage racing style, 2 túi trước tiện dụng.',
    shortDescription: 'Zip full | Kẻ sọc vintage | 2 túi trước',
    images: [img('hoodie-speed-1'), img('hoodie-speed-2')],
    category: 'ao', subCategory: 'ao-hoodie',
    tags: ['f1', 'retro', 'streetwear'],
    basePrice: 649000, material: 'Cotton 80%, Polyester 20%',
    careInstructions: CARE,
    variants: variants(FULL, [RED, BLACK, NAVY]),
    rating: { average: 4.8, count: 234 }, soldCount: 870, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Lap Record',
    slug: 'ao-thun-bobo-lap-record',
    description: 'In đồng hồ bấm giờ và record time nổi tiếng. Cotton 100% wash nhẹ aged finish.',
    shortDescription: 'Lap record print | Aged finish | Cotton',
    images: [img('laprecord-tee-1'), img('laprecord-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'graphic', 'vintage'],
    basePrice: 329000, material: 'Cotton 100%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, GRAY, WHITE]),
    rating: { average: 4.6, count: 178 }, soldCount: 610, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Aero Dynamic',
    slug: 'ao-thun-bobo-aero-dynamic',
    description: 'Form aerodynamic với đường seam vát bên hông, vải DryFit thoáng khí hoàn hảo.',
    shortDescription: 'Seam vát | DryFit | Aerodynamic fit',
    images: [img('aero-tee-1'), img('aero-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['technical', 'racing', 'sport'],
    basePrice: 349000, material: 'Polyester 88%, Spandex 12%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, RED, BLUE]),
    rating: { average: 4.7, count: 203 }, soldCount: 750, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo BoBo Fleece Racing Crewneck',
    slug: 'ao-bobo-fleece-racing-crewneck',
    description: 'Sweatshirt cổ tròn chất fleece dày dặn, bo gấu và tay nổi bật, phong cách retro 90s.',
    shortDescription: 'Fleece dày | Bo nổi | Retro 90s',
    images: [img('fleece-crewneck-1'), img('fleece-crewneck-2')],
    category: 'ao', subCategory: 'ao-sweater',
    tags: ['retro', 'f1', 'streetwear'],
    basePrice: 499000, material: 'Cotton 60%, Polyester 40% Fleece',
    careInstructions: CARE,
    variants: variants(FULL, [GRAY, BLACK, NAVY, RED]),
    rating: { average: 4.7, count: 267 }, soldCount: 920, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo BoBo Racing Vest Knit',
    slug: 'ao-bobo-racing-vest-knit',
    description: 'Vest len dệt kim không tay, hoạ tiết kẻ polo retro, phối shirt hoặc turtleneck đều chuẩn.',
    shortDescription: 'Vest len | Kẻ polo retro | Phối đa năng',
    images: [img('vest-knit-racing-1'), img('vest-knit-racing-2')],
    category: 'ao', subCategory: 'ao-vest',
    tags: ['f1', 'retro', 'knit', 'trending'],
    basePrice: 549000, material: 'Acrylic 70%, Wool 30%',
    careInstructions: ['Giặt tay nước lạnh'],
    variants: variants(STD, [NAVY, RED, CREAM]),
    rating: { average: 4.8, count: 345 }, soldCount: 1230, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Helmet Graphic',
    slug: 'ao-thun-bobo-helmet-graphic',
    description: 'In hình mũ bảo hiểm F1 full màu theo phong cách street art. Form unisex thoải mái.',
    shortDescription: 'Helmet art print | Street art | Unisex',
    images: [img('helmet-graphic-tee-1'), img('helmet-graphic-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'graphic', 'unisex', 'trending'],
    basePrice: 359000, material: 'Cotton 100%',
    careInstructions: CARE,
    variants: variants(FULL, [WHITE, BLACK]),
    rating: { average: 4.9, count: 412 }, soldCount: 1780, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo BoBo Racing Flag Polo',
    slug: 'ao-bobo-racing-flag-polo',
    description: 'Polo in cờ các quốc gia đua xe nhỏ ở ngực trái, tôn vinh văn hóa F1 toàn cầu.',
    shortDescription: 'Cờ racing nations | Ngực trái | F1 culture',
    images: [img('flag-polo-racing-1'), img('flag-polo-racing-2')],
    category: 'ao', subCategory: 'ao-polo',
    tags: ['f1', 'culture', 'new-arrival'],
    basePrice: 429000, material: 'Pique Cotton 60%, Polyester 40%',
    careInstructions: CARE,
    variants: variants(STD, [WHITE, BLACK, NAVY]),
    rating: { average: 4.7, count: 156 }, soldCount: 530, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Sơ Mi BoBo Oversize Race Day',
    slug: 'ao-so-mi-bobo-oversize-race-day',
    description: 'Sơ mi oversized form thùng thụng, họa tiết hình xe đua nhỏ scatter print. Mặc nhà hoặc dạo phố.',
    shortDescription: 'Oversized | Scatter car print | Đa năng',
    images: [img('oversize-shirt-raceday-1'), img('oversize-shirt-raceday-2')],
    category: 'ao', subCategory: 'ao-so-mi',
    tags: ['f1', 'oversized', 'casual'],
    basePrice: 479000, material: 'Cotton Oxford 100%',
    careInstructions: CARE,
    variants: variants(STD, [WHITE, CREAM, BLUE]),
    rating: { average: 4.6, count: 143 }, soldCount: 480, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Slipstream',
    slug: 'ao-thun-bobo-slipstream',
    description: 'In hoạ tiết luồng khí động học trừu tượng, gradient từ đen sang xám. Nghệ thuật kỹ thuật.',
    shortDescription: 'Khí động học art | Gradient | Nghệ thuật',
    images: [img('slipstream-tee-1'), img('slipstream-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'art', 'premium'],
    basePrice: 379000, material: 'Cotton 100% 180gsm',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, CARBON]),
    rating: { average: 4.7, count: 190 }, soldCount: 670, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo BoBo DRS Zone Tee',
    slug: 'ao-bobo-drs-zone-tee',
    description: '"DRS ZONE" in chữ to phản quang ở lưng. Đêm tối bùng nổ, ban ngày tối giản.',
    shortDescription: 'DRS phản quang | Tối giản ngày | Bùng nổ đêm',
    images: [img('drs-tee-1'), img('drs-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'reflective', 'streetwear'],
    basePrice: 399000, material: 'Cotton 100%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, NAVY]),
    rating: { average: 4.8, count: 223 }, soldCount: 840, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Safety Car',
    slug: 'ao-thun-bobo-safety-car',
    description: 'In hình chiếc xe Safety Car biểu tượng F1, cotton 100% wash nhẹ retro look. Dân F1 chắc thích.',
    shortDescription: 'Safety Car print | Retro look | Cotton',
    images: [img('safety-car-tee-1'), img('safety-car-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'graphic', 'retro', 'new-arrival'],
    basePrice: 339000, material: 'Cotton 100%',
    careInstructions: CARE,
    variants: variants(FULL, [YELLOW, BLACK, WHITE]),
    rating: { average: 4.7, count: 178 }, soldCount: 620, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Khoác Denim BoBo Garage',
    slug: 'ao-khoac-denim-bobo-garage',
    description: 'Denim jacket wash medium với patches thêu logo garage và số xe đua. Biểu tượng phong cách.',
    shortDescription: 'Denim wash | Garage patches | Iconic',
    images: [img('denim-jacket-garage-1'), img('denim-jacket-garage-2')],
    category: 'outerwear', subCategory: 'ao-khoac-denim',
    tags: ['f1', 'racing', 'denim', 'new-arrival'],
    basePrice: 1190000, material: 'Denim Cotton 100% 12oz',
    careInstructions: CARE,
    variants: variants(STD, [{ color: 'Xanh Denim', hex: '#1560BD', skuCode: 'DNM' }, BLACK]),
    rating: { average: 4.8, count: 167 }, soldCount: 530, isFeatured: true, isActive: true,
  },
  {
    name: 'Áo Polo BoBo Williams Racing',
    slug: 'ao-polo-bobo-williams-racing',
    description: 'Phối xanh dương đặc trưng Williams Racing, thêu số 3 ngực trái, vải pique thoáng mát.',
    shortDescription: 'Williams Blue | Số 3 thêu | Pique thoáng',
    images: [img('polo-williams-blue-1'), img('polo-williams-blue-2')],
    category: 'ao', subCategory: 'ao-polo',
    tags: ['f1', 'williams', 'racing'],
    basePrice: 399000, material: 'Pique Cotton 60%, Polyester 40%',
    careInstructions: CARE,
    variants: variants(STD, [{ color: 'Xanh Williams', hex: '#0057A0', skuCode: 'WBL' }, WHITE, BLACK]),
    rating: { average: 4.6, count: 112 }, soldCount: 380, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Thun BoBo Pit Board',
    slug: 'ao-thun-bobo-pit-board',
    description: 'In hình bảng hiển thị pit stop với vòng đua, thời gian lap và thứ hạng. Thông điệp race từng giây.',
    shortDescription: 'Pit board print | Lap time | Race data',
    images: [img('pit-board-tee-1'), img('pit-board-tee-2')],
    category: 'ao', subCategory: 'ao-thun',
    tags: ['f1', 'graphic', 'data', 'nerd'],
    basePrice: 359000, material: 'Cotton 100% 200gsm',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, WHITE, NAVY]),
    rating: { average: 4.7, count: 201 }, soldCount: 730, isFeatured: false, isActive: true,
  },
  {
    name: 'Áo Hoodie BoBo Undercut Racing',
    slug: 'ao-hoodie-bobo-undercut-racing',
    description: 'Hoodie crop tay dài tạo kiểu undercut bên hông, phong cách streetwear racing nổi bật.',
    shortDescription: 'Crop undercut | Streetwear | Racing bold',
    images: [img('hoodie-undercut-racing-1'), img('hoodie-undercut-racing-2')],
    category: 'ao', subCategory: 'ao-hoodie',
    tags: ['f1', 'streetwear', 'women', 'trending'],
    basePrice: 579000, material: 'Cotton 80%, Polyester 20%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, RED, WHITE]),
    rating: { average: 4.8, count: 256 }, soldCount: 940, isFeatured: false, isActive: true,
  },

  // =========================================================================
  // QUẦN (36–58)
  // =========================================================================
  {
    name: 'Quần Track BoBo Motorsport',
    slug: 'quan-track-bobo-motorsport',
    description: 'Quần track pants sọc bên, cạp chun thun co giãn thoải mái. Đi tập hay dạo phố đều ổn.',
    shortDescription: 'Sọc bên | Cạp chun | Co giãn',
    images: [img('track-pants-1'), img('track-pants-2')],
    category: 'quan', subCategory: 'quan-track',
    tags: ['f1', 'sport', 'new-arrival', 'best-seller'],
    basePrice: 499000, material: 'Polyester 100%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, NAVY, RED]),
    rating: { average: 4.8, count: 489 }, soldCount: 2100, isFeatured: true, isActive: true,
  },
  {
    name: 'Quần Track BoBo McLaren Orange Stripe',
    slug: 'quan-track-bobo-mclaren-orange-stripe',
    description: 'Sọc cam McLaren bắt mắt trên nền đen, co giãn tốt, túi zip bên hông.',
    shortDescription: 'Orange stripe | Túi zip | Co giãn',
    images: [img('track-pants-orange-1'), img('track-pants-orange-2')],
    category: 'quan', subCategory: 'quan-track',
    tags: ['f1', 'mclaren', 'sport'],
    basePrice: 529000, salePrice: 459000, discountPercent: 13,
    material: 'Polyester 100%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK]),
    rating: { average: 4.7, count: 234 }, soldCount: 890, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Cargo BoBo Pit Crew',
    slug: 'quan-cargo-bobo-pit-crew',
    description: 'Cargo pants kỹ thuật với 6 túi hộp, chất ripstop bền bỉ, kiểu dáng pit crew chuyên nghiệp.',
    shortDescription: '6 túi hộp | Ripstop | Pit crew style',
    images: [img('cargo-pitcrew-1'), img('cargo-pitcrew-2')],
    category: 'quan', subCategory: 'quan-cargo',
    tags: ['f1', 'workwear', 'utility', 'new-arrival'],
    basePrice: 699000, material: 'Cotton Ripstop 100%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, KHAKI, NAVY]),
    rating: { average: 4.7, count: 312 }, soldCount: 1100, isFeatured: true, isActive: true,
  },
  {
    name: 'Quần Cargo BoBo Tactical Racing',
    slug: 'quan-cargo-bobo-tactical-racing',
    description: 'Cargo tactical với velcro tabs và D-ring móc phụ kiện. Phong cách race-ready ngoài đường đua.',
    shortDescription: 'Velcro tabs | D-ring | Tactical',
    images: [img('cargo-tactical-1'), img('cargo-tactical-2')],
    category: 'quan', subCategory: 'quan-cargo',
    tags: ['tactical', 'racing', 'utility'],
    basePrice: 749000, material: 'Nylon Ripstop 65%, Cotton 35%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, KHAKI]),
    rating: { average: 4.6, count: 167 }, soldCount: 530, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Jean BoBo Slim Racing Wash',
    slug: 'quan-jean-bobo-slim-racing-wash',
    description: 'Jean slim fit wash xước nhẹ gợi liên tưởng garage cơ học. Co giãn tốt, đứng form cả ngày.',
    shortDescription: 'Racing wash | Slim fit | Co giãn',
    images: [img('jean-racing-wash-1'), img('jean-racing-wash-2')],
    category: 'quan', subCategory: 'quan-jean',
    tags: ['casual', 'racing', 'best-seller'],
    basePrice: 649000, material: 'Denim 98%, Spandex 2%',
    careInstructions: CARE,
    variants: variants(STD, [{ color: 'Xanh Nhạt', hex: '#ADD8E6', skuCode: 'LBL' }, { color: 'Đen', hex: '#1A1A1A', skuCode: 'BLK' }]),
    rating: { average: 4.8, count: 423 }, soldCount: 1780, isFeatured: true, isActive: true,
  },
  {
    name: 'Quần Jean BoBo Straight Monaco',
    slug: 'quan-jean-bobo-straight-monaco',
    description: 'Jean straight leg lấy cảm hứng từ phố đêm Monaco, wash indigo đậm sang trọng.',
    shortDescription: 'Straight leg | Indigo đậm | Monaco style',
    images: [img('jean-straight-monaco-1'), img('jean-straight-monaco-2')],
    category: 'quan', subCategory: 'quan-jean',
    tags: ['casual', 'premium', 'monaco'],
    basePrice: 699000, material: 'Denim 100% 12oz',
    careInstructions: CARE,
    variants: variants(STD, [{ color: 'Indigo', hex: '#4B0082', skuCode: 'IND' }, { color: 'Đen', hex: '#1A1A1A', skuCode: 'BLK' }]),
    rating: { average: 4.7, count: 198 }, soldCount: 720, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Kaki BoBo Paddock Chino',
    slug: 'quan-kaki-bobo-paddock-chino',
    description: 'Chino slim fit cotton twill nhẹ, phong cách paddock VIP. Phối polo hoặc sơ mi đều đẹp.',
    shortDescription: 'Cotton twill | Slim fit | Paddock VIP',
    images: [img('chino-paddock-1'), img('chino-paddock-2')],
    category: 'quan', subCategory: 'quan-kaki',
    tags: ['elegant', 'paddock', 'casual'],
    basePrice: 599000, material: 'Cotton Twill 100%',
    careInstructions: CARE,
    variants: variants(STD, [KHAKI, NAVY, BLACK]),
    rating: { average: 4.6, count: 245 }, soldCount: 860, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Short BoBo Racing Bermuda',
    slug: 'quan-short-bobo-racing-bermuda',
    description: 'Quần short bermuda vải dù nhẹ, in số vòng đua sublimation, cạp dây rút tiện lợi.',
    shortDescription: 'Vải dù nhẹ | Sublimation print | Cạp dây rút',
    images: [img('shorts-bermuda-racing-1'), img('shorts-bermuda-racing-2')],
    category: 'quan', subCategory: 'quan-short',
    tags: ['f1', 'summer', 'sport'],
    basePrice: 379000, material: 'Polyester 100%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, NAVY, RED]),
    rating: { average: 4.7, count: 312 }, soldCount: 1240, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Short BoBo Swim Racing',
    slug: 'quan-short-bobo-swim-racing',
    description: 'Board short nhanh khô với in đường đua sublimation. Từ hồ bơi đến pool party đều stylish.',
    shortDescription: 'Nhanh khô | Board short | Pool party',
    images: [img('boardshort-racing-1'), img('boardshort-racing-2')],
    category: 'quan', subCategory: 'quan-short',
    tags: ['summer', 'swim', 'f1'],
    basePrice: 349000, material: 'Polyester 100% Quick-dry',
    careInstructions: ['Giặt tay nước lạnh'],
    variants: variants(STD, [BLACK, { color: 'Xanh Racing', hex: '#0055A4', skuCode: 'BRG' }]),
    rating: { average: 4.5, count: 189 }, soldCount: 650, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần BoBo Straight Carbon',
    slug: 'quan-bobo-straight-carbon',
    description: 'Quần vải tuyết mưa pha cotton, màu carbon matte, túi slant trước sau chắc chắn.',
    shortDescription: 'Tuyết mưa | Carbon matte | Slant pockets',
    images: [img('straight-carbon-pants-1'), img('straight-carbon-pants-2')],
    category: 'quan', subCategory: 'quan-kaki',
    tags: ['f1', 'elegant', 'premium'],
    basePrice: 629000, material: 'Polyester 65%, Rayon 35%',
    careInstructions: CARE,
    variants: variants(STD, [CARBON, BLACK, NAVY]),
    rating: { average: 4.6, count: 145 }, soldCount: 490, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Jogger BoBo Pit Stop',
    slug: 'quan-jogger-bobo-pit-stop',
    description: 'Jogger cổ chân bo chun, in số vòng đua dọc sọc ống. Mặc nhà, tập gym, dạo phố.',
    shortDescription: 'Bo chun cổ chân | Số vòng đua | Đa năng',
    images: [img('jogger-pitstop-1'), img('jogger-pitstop-2')],
    category: 'quan', subCategory: 'quan-jogger',
    tags: ['f1', 'casual', 'sport'],
    basePrice: 479000, material: 'Cotton 70%, Polyester 30%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, GRAY, NAVY]),
    rating: { average: 4.7, count: 289 }, soldCount: 1020, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Kaki BoBo Grid Start',
    slug: 'quan-kaki-bobo-grid-start',
    description: 'Chino ống suôn có pleat trước kiểu dáng vintage race driver, phối áo polo hay turtleneck.',
    shortDescription: 'Pleat vintage | Ống suôn | Driver style',
    images: [img('chino-gridstart-1'), img('chino-gridstart-2')],
    category: 'quan', subCategory: 'quan-kaki',
    tags: ['f1', 'vintage', 'elegant'],
    basePrice: 649000, material: 'Cotton Chino 100%',
    careInstructions: CARE,
    variants: variants(STD, [KHAKI, CREAM, NAVY]),
    rating: { average: 4.5, count: 98 }, soldCount: 310, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Jean BoBo Moto Biker',
    slug: 'quan-jean-bobo-moto-biker',
    description: 'Jean biker với panel overlay đầu gối, túi chéo trước, wash dark tone chất mạnh.',
    shortDescription: 'Panel đầu gối | Túi chéo | Dark wash',
    images: [img('biker-jean-1'), img('biker-jean-2')],
    category: 'quan', subCategory: 'quan-jean',
    tags: ['racing', 'biker', 'streetwear'],
    basePrice: 799000, material: 'Denim 98%, Spandex 2%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, { color: 'Dark Indigo', hex: '#1B1464', skuCode: 'DIN' }]),
    rating: { average: 4.6, count: 167 }, soldCount: 560, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Track BoBo Silver Arrow',
    slug: 'quan-track-bobo-silver-arrow',
    description: 'Track pants màu xám bạc gợi liên tưởng Silver Arrow Mercedes, vải tuyết mưa cao cấp.',
    shortDescription: 'Silver Arrow tone | Tuyết mưa | Cao cấp',
    images: [img('track-pants-silver-1'), img('track-pants-silver-2')],
    category: 'quan', subCategory: 'quan-track',
    tags: ['f1', 'mercedes', 'premium'],
    basePrice: 579000, material: 'Polyester 80%, Nylon 20%',
    careInstructions: CARE,
    variants: variants(FULL, [SILVER, BLACK]),
    rating: { average: 4.7, count: 178 }, soldCount: 630, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Short BoBo Paddock Tech',
    slug: 'quan-short-bobo-paddock-tech',
    description: 'Short kỹ thuật 4 chiều co giãn, vải quick-dry thoáng mát, cạp có vòng belt loops.',
    shortDescription: '4 chiều co giãn | Quick-dry | Belt loops',
    images: [img('short-paddock-tech-1'), img('short-paddock-tech-2')],
    category: 'quan', subCategory: 'quan-short',
    tags: ['technical', 'sport', 'paddock'],
    basePrice: 399000, material: 'Polyester 85%, Spandex 15%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, NAVY, GRAY]),
    rating: { average: 4.8, count: 256 }, soldCount: 940, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Legging BoBo Race Speed',
    slug: 'quan-legging-bobo-race-speed',
    description: 'Legging co giãn 4 chiều in sọc tốc độ bên hông, cạp cao định hình, vải DryFit mềm mịn.',
    shortDescription: 'Co giãn 4 chiều | Sọc tốc độ | Cạp cao',
    images: [img('legging-race-speed-1'), img('legging-race-speed-2')],
    category: 'quan', subCategory: 'quan-legging',
    tags: ['sport', 'women', 'racing', 'new-arrival'],
    basePrice: 429000, material: 'Polyester 80%, Spandex 20%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, NAVY, RED]),
    rating: { average: 4.8, count: 312 }, soldCount: 1180, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Jean BoBo Baggy Garage',
    slug: 'quan-jean-bobo-baggy-garage',
    description: 'Jean baggy wide-leg phong cách thợ garage, wash nhẹ với mảng sơn nhỏ trang trí. Bold và cá tính.',
    shortDescription: 'Baggy wide-leg | Garage wash | Bold',
    images: [img('baggy-jean-garage-1'), img('baggy-jean-garage-2')],
    category: 'quan', subCategory: 'quan-jean',
    tags: ['racing', 'streetwear', 'oversized', 'new-arrival'],
    basePrice: 749000, material: 'Denim Cotton 100% 12oz',
    careInstructions: CARE,
    variants: variants(STD, [{ color: 'Xanh Wash', hex: '#5B92C4', skuCode: 'WSH' }, CARBON]),
    rating: { average: 4.7, count: 189 }, soldCount: 640, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Cargo BoBo 3/4 Tech',
    slug: 'quan-cargo-bobo-3-4-tech',
    description: 'Cargo 3/4 dưới gối với túi hộp nhiều lớp, khóa kéo YKK, phong cách race mechanic casual.',
    shortDescription: 'Cargo 3/4 | YKK zip | Mechanic casual',
    images: [img('cargo-3-4-tech-1'), img('cargo-3-4-tech-2')],
    category: 'quan', subCategory: 'quan-cargo',
    tags: ['f1', 'utility', 'casual'],
    basePrice: 619000, material: 'Cotton Ripstop 65%, Polyester 35%',
    careInstructions: CARE,
    variants: variants(STD, [KHAKI, BLACK, NAVY]),
    rating: { average: 4.6, count: 145 }, soldCount: 490, isFeatured: false, isActive: true,
  },
  {
    name: 'Quần Short BoBo F1 Lounge',
    slug: 'quan-short-bobo-f1-lounge',
    description: 'Short cotton mềm mịn mặc nhà in số liệu telemetry F1. Thoải mái cả ngày, fan F1 sẽ hiểu.',
    shortDescription: 'Cotton mềm | Telemetry print | Lounge wear',
    images: [img('lounge-short-f1-1'), img('lounge-short-f1-2')],
    category: 'quan', subCategory: 'quan-short',
    tags: ['f1', 'lounge', 'fun', 'casual'],
    basePrice: 299000, material: 'Cotton 100%',
    careInstructions: CARE,
    variants: variants(FULL, [BLACK, GRAY, NAVY]),
    rating: { average: 4.6, count: 234 }, soldCount: 870, isFeatured: false, isActive: true,
  },

  // =========================================================================
  // VÁY / ĐẦM (59–68)
  // =========================================================================
  {
    name: 'Váy Mini BoBo Race Queen',
    slug: 'vay-mini-bobo-race-queen',
    description: 'Váy mini co giãn in hoạ tiết cờ ca rô racing bao phủ toàn thân. Mạnh mẽ, cá tính.',
    shortDescription: 'Cờ ca rô racing | Mini | Co giãn',
    images: [img('mini-skirt-racequeen-1'), img('mini-skirt-racequeen-2')],
    category: 'vay', subCategory: 'vay-mini',
    tags: ['f1', 'women', 'trending', 'new-arrival'],
    basePrice: 379000, material: 'Spandex 30%, Cotton 70%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, WHITE, RED]),
    rating: { average: 4.9, count: 423 }, soldCount: 1760, isFeatured: true, isActive: true,
  },
  {
    name: 'Váy Midi BoBo Paddock Lady',
    slug: 'vay-midi-bobo-paddock-lady',
    description: 'Váy midi vải crepe sang trọng, xẻ sọc bên tinh tế. Phong cách paddock VIP.',
    shortDescription: 'Crepe sang trọng | Xẻ sọc | Paddock VIP',
    images: [img('midi-skirt-paddock-1'), img('midi-skirt-paddock-2')],
    category: 'vay', subCategory: 'vay-midi',
    tags: ['f1', 'elegant', 'women'],
    basePrice: 549000, material: 'Crepe Polyester 100%',
    careInstructions: ['Giặt tay nhẹ', 'Phơi thẳng'],
    variants: variants(STD, [BLACK, NAVY, RED]),
    rating: { average: 4.8, count: 178 }, soldCount: 640, isFeatured: false, isActive: true,
  },
  {
    name: 'Đầm BoBo Wrap Racing Stripes',
    slug: 'dam-bobo-wrap-racing-stripes',
    description: 'Đầm wrap quấn với sọc dọc dài tôn dáng, cổ V nhẹ nhàng, phong cách podium glamour.',
    shortDescription: 'Wrap quấn | Sọc dọc | Podium glamour',
    images: [img('wrap-dress-racing-1'), img('wrap-dress-racing-2')],
    category: 'dam', subCategory: 'dam-wrap',
    tags: ['f1', 'women', 'elegant', 'new-arrival'],
    basePrice: 699000, material: 'Viscose 100%',
    careInstructions: ['Giặt tay nước lạnh'],
    variants: variants(STD, [BLACK, RED, WHITE]),
    rating: { average: 4.8, count: 212 }, soldCount: 780, isFeatured: true, isActive: true,
  },
  {
    name: 'Đầm BoBo Slip Checkered',
    slug: 'dam-bobo-slip-checkered',
    description: 'Slip dress lụa nhân tạo in cờ ca rô đen trắng tinh tế. Mặc một mình hoặc layering.',
    shortDescription: 'Lụa nhân tạo | Ca rô đen trắng | Layering',
    images: [img('slip-dress-checkered-1'), img('slip-dress-checkered-2')],
    category: 'dam', subCategory: 'dam-slip',
    tags: ['f1', 'women', 'elegant'],
    basePrice: 599000, material: 'Satin Polyester 100%',
    careInstructions: ['Giặt tay nước lạnh'],
    variants: variants(STD, [{ color: 'Đen - Trắng', hex: '#000000', skuCode: 'BNW' }]),
    rating: { average: 4.7, count: 134 }, soldCount: 430, isFeatured: false, isActive: true,
  },
  {
    name: 'Váy BoBo Denim Racing Mini',
    slug: 'vay-bobo-denim-racing-mini',
    description: 'Chân váy denim ngắn với patch thêu racing, cạp cao tôn eo, phối crop top đỉnh.',
    shortDescription: 'Denim patch | Cạp cao | Phối crop',
    images: [img('denim-miniskirt-racing-1'), img('denim-miniskirt-racing-2')],
    category: 'vay', subCategory: 'vay-denim',
    tags: ['f1', 'women', 'casual', 'trending'],
    basePrice: 459000, material: 'Denim Cotton 100%',
    careInstructions: CARE,
    variants: variants(STD, [{ color: 'Xanh Denim', hex: '#1560BD', skuCode: 'DNM' }, BLACK]),
    rating: { average: 4.8, count: 267 }, soldCount: 1020, isFeatured: false, isActive: true,
  },
  {
    name: 'Đầm BoBo Co-ord Racing Set',
    slug: 'dam-bobo-coord-racing-set',
    description: 'Bộ co-ord bao gồm áo thun + váy midi ton-sur-ton racing stripes. Mặc cả bộ hoặc mix.',
    shortDescription: 'Co-ord set | Racing stripes | Mix & match',
    images: [img('coord-racing-set-1'), img('coord-racing-set-2')],
    category: 'dam', subCategory: 'bo-ao-vay',
    tags: ['f1', 'women', 'set', 'new-arrival'],
    basePrice: 799000, material: 'Spandex 20%, Cotton 80%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, RED, NAVY]),
    rating: { average: 4.9, count: 312 }, soldCount: 1240, isFeatured: true, isActive: true,
  },
  {
    name: 'Váy Skort BoBo Pit Lane',
    slug: 'vay-skort-bobo-pit-lane',
    description: 'Skort (váy có quần trong) vải thể thao, thoải mái di chuyển, in logo nhỏ bên hông.',
    shortDescription: 'Váy + quần trong | Thể thao | Thoải mái',
    images: [img('skort-pitlane-1'), img('skort-pitlane-2')],
    category: 'vay', subCategory: 'vay-skort',
    tags: ['sport', 'women', 'casual'],
    basePrice: 399000, material: 'Polyester 88%, Spandex 12%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, NAVY, WHITE]),
    rating: { average: 4.7, count: 189 }, soldCount: 680, isFeatured: false, isActive: true,
  },
  {
    name: 'Váy Pleated BoBo Trophy Wife',
    slug: 'vay-pleated-bobo-trophy-wife',
    description: 'Váy xếp ly midi dáng xòe sang trọng, màu kem gợi cảm podium. Đi sự kiện hay gallery.',
    shortDescription: 'Xếp ly midi | Xòe | Podium elegance',
    images: [img('pleated-skirt-trophy-1'), img('pleated-skirt-trophy-2')],
    category: 'vay', subCategory: 'vay-pleated',
    tags: ['f1', 'elegant', 'women', 'event'],
    basePrice: 649000, material: 'Chiffon Polyester 100%',
    careInstructions: ['Giặt tay nhẹ'],
    variants: variants(STD, [CREAM, BLACK, SILVER]),
    rating: { average: 4.8, count: 145 }, soldCount: 490, isFeatured: false, isActive: true,
  },
  {
    name: 'Đầm BoBo Asymmetric Circuit',
    slug: 'dam-bobo-asymmetric-circuit',
    description: 'Đầm hem bất đối xứng dài ngắn độc đáo, tone đen mạnh mẽ, phong cách circuit night.',
    shortDescription: 'Hem bất đối xứng | Đen mạnh mẽ | Night event',
    images: [img('asymmetric-dress-circuit-1'), img('asymmetric-dress-circuit-2')],
    category: 'dam', subCategory: 'dam-bat-doi-xung',
    tags: ['f1', 'women', 'event', 'premium'],
    basePrice: 899000, material: 'Scuba Crepe 100%',
    careInstructions: ['Giặt tay nước lạnh'],
    variants: variants(STD, [BLACK, RED]),
    rating: { average: 4.7, count: 89 }, soldCount: 280, isFeatured: false, isActive: true,
  },
  {
    name: 'Váy BoBo Grid Girl Mini',
    slug: 'vay-bobo-grid-girl-mini',
    description: 'Váy mini bodycon kẻ sọc đua màu sắc, co giãn mạnh, cổ tròn sát cổ kiểu cao.',
    shortDescription: 'Bodycon | Sọc đua | Co giãn mạnh',
    images: [img('mini-grid-girl-1'), img('mini-grid-girl-2')],
    category: 'vay', subCategory: 'vay-bodycon',
    tags: ['f1', 'women', 'trending', 'bold'],
    basePrice: 429000, material: 'Spandex 40%, Rayon 60%',
    careInstructions: CARE,
    variants: variants(STD, [RED, BLACK, WHITE]),
    rating: { average: 4.8, count: 234 }, soldCount: 890, isFeatured: false, isActive: true,
  },
  {
    name: 'Váy Tube BoBo Circuit Babe',
    slug: 'vay-tube-bobo-circuit-babe',
    description: 'Váy tube quây bandeau in họa tiết đường đua, chất co giãn bó sát, chuẩn street summer.',
    shortDescription: 'Bandeau tube | Đường đua print | Summer street',
    images: [img('tube-skirt-circuit-1'), img('tube-skirt-circuit-2')],
    category: 'vay', subCategory: 'vay-tube',
    tags: ['f1', 'women', 'summer', 'trending', 'new-arrival'],
    basePrice: 349000, material: 'Spandex 35%, Rayon 65%',
    careInstructions: CARE,
    variants: variants(STD, [BLACK, RED, WHITE]),
    rating: { average: 4.8, count: 289 }, soldCount: 1060, isFeatured: false, isActive: true,
  },
  {
    name: 'Đầm BoBo Mini Race Night',
    slug: 'dam-bobo-mini-race-night',
    description: 'Đầm mini dáng shift không tay, vải thun gân sọc dọc màu đen, phong cách circuit night out.',
    shortDescription: 'Shift mini | Gân sọc dọc | Night out',
    images: [img('mini-dress-race-night-1'), img('mini-dress-race-night-2')],
    category: 'dam', subCategory: 'dam-mini',
    tags: ['f1', 'women', 'evening', 'new-arrival'],
    basePrice: 649000, material: 'Viscose Rib 95%, Spandex 5%',
    careInstructions: ['Giặt tay nước lạnh'],
    variants: variants(STD, [BLACK, RED, NAVY]),
    rating: { average: 4.7, count: 156 }, soldCount: 550, isFeatured: false, isActive: true,
  },

  // =========================================================================
  // PHỤ KIỆN (69–100)
  // =========================================================================
  {
    name: 'Mũ Snapback BoBo Racing',
    slug: 'mu-snapback-bobo-racing',
    description: 'Snapback 6-panel vải thun, logo BoBo thêu nổi trước, strap điều chỉnh sau. Unisex.',
    shortDescription: '6-panel thêu nổi | Strap điều chỉnh | Unisex',
    images: [img('snapback-racing-1'), img('snapback-racing-2')],
    category: 'phu-kien', subCategory: 'mu',
    tags: ['f1', 'accessories', 'best-seller', 'new-arrival'],
    basePrice: 299000, material: 'Polyester 100%',
    variants: variants(OS, [BLACK, RED, NAVY, WHITE]),
    rating: { average: 4.8, count: 678 }, soldCount: 3200, isFeatured: true, isActive: true,
  },
  {
    name: 'Mũ Dad Hat BoBo Paddock',
    slug: 'mu-dad-hat-bobo-paddock',
    description: 'Dad hat low-profile vải cotton wash nhẹ, logo BoBo thêu tone-on-tone. Tối giản sang trọng.',
    shortDescription: 'Low-profile | Tone-on-tone | Tối giản',
    images: [img('dad-hat-paddock-1'), img('dad-hat-paddock-2')],
    category: 'phu-kien', subCategory: 'mu',
    tags: ['f1', 'accessories', 'elegant'],
    basePrice: 279000, material: 'Cotton 100%',
    variants: variants(OS, [BLACK, CREAM, NAVY]),
    rating: { average: 4.7, count: 445 }, soldCount: 1980, isFeatured: false, isActive: true,
  },
  {
    name: 'Mũ Bucket BoBo Circuit',
    slug: 'mu-bucket-bobo-circuit',
    description: 'Bucket hat vành rộng in bản đồ đường đua toàn thân, chống nắng tốt, gấp gọn tiện lợi.',
    shortDescription: 'In bản đồ đường đua | Chống nắng | Gấp gọn',
    images: [img('bucket-hat-circuit-1'), img('bucket-hat-circuit-2')],
    category: 'phu-kien', subCategory: 'mu',
    tags: ['f1', 'accessories', 'summer'],
    basePrice: 319000, material: 'Cotton 100%',
    variants: variants(OS, [BLACK, WHITE, NAVY]),
    rating: { average: 4.6, count: 312 }, soldCount: 1100, isFeatured: false, isActive: true,
  },
  {
    name: 'Mũ Beret BoBo Podium',
    slug: 'mu-beret-bobo-podium',
    description: 'Beret len mềm logo BoBo thêu bạc, kiểu dáng châu Âu sang trọng, phong cách podium.',
    shortDescription: 'Beret len | Thêu bạc | Podium châu Âu',
    images: [img('beret-podium-1'), img('beret-podium-2')],
    category: 'phu-kien', subCategory: 'mu',
    tags: ['f1', 'elegant', 'accessories'],
    basePrice: 349000, material: 'Wool 80%, Acrylic 20%',
    variants: variants(OS, [BLACK, RED, NAVY]),
    rating: { average: 4.7, count: 189 }, soldCount: 670, isFeatured: false, isActive: true,
  },
  {
    name: 'Dây Lưng BoBo Racing Carbon',
    slug: 'day-lung-bobo-racing-carbon',
    description: 'Dây lưng da PU vân carbon fiber, khóa kim loại nặng mạ chrome, logo BoBo khắc nổi.',
    shortDescription: 'Da PU vân carbon | Khóa chrome | Khắc logo',
    images: [img('belt-carbon-racing-1'), img('belt-carbon-racing-2')],
    category: 'phu-kien', subCategory: 'day-lung',
    tags: ['f1', 'accessories', 'premium'],
    basePrice: 399000, material: 'PU Leather cao cấp',
    variants: variants(OS, [BLACK, CARBON]),
    rating: { average: 4.8, count: 234 }, soldCount: 890, isFeatured: true, isActive: true,
  },
  {
    name: 'Dây Lưng BoBo Webbing Stripe',
    slug: 'day-lung-bobo-webbing-stripe',
    description: 'Dây lưng vải nylon dệt kẻ sọc màu đua, khóa click-release nhanh, dễ điều chỉnh.',
    shortDescription: 'Nylon kẻ sọc | Click-release | Điều chỉnh dễ',
    images: [img('belt-webbing-stripe-1')],
    category: 'phu-kien', subCategory: 'day-lung',
    tags: ['f1', 'accessories', 'casual'],
    basePrice: 249000, material: 'Nylon Webbing',
    variants: variants(OS, [RED, BLUE, BLACK]),
    rating: { average: 4.6, count: 178 }, soldCount: 680, isFeatured: false, isActive: true,
  },
  {
    name: 'Túi Tote BoBo Pit Crew Canvas',
    slug: 'tui-tote-bobo-pit-crew-canvas',
    description: 'Tote canvas dày in số xe racing, quai dài thoải mái, dung tích lớn đựng đủ thứ.',
    shortDescription: 'Canvas dày | Số xe racing | Dung tích lớn',
    images: [img('tote-pitcrew-canvas-1')],
    category: 'phu-kien', subCategory: 'tui-tote',
    tags: ['f1', 'accessories', 'best-seller'],
    basePrice: 229000, material: 'Canvas Cotton 12oz',
    variants: variants(OS, [CREAM, BLACK, NAVY]),
    rating: { average: 4.7, count: 512 }, soldCount: 2340, isFeatured: true, isActive: true,
  },
  {
    name: 'Túi Messenger BoBo Paddock',
    slug: 'tui-messenger-bobo-paddock',
    description: 'Messenger bag vải ballistic nylon kháng nước, ngăn laptop 13", khóa YKK toàn bộ.',
    shortDescription: 'Ballistic nylon | Ngăn laptop 13" | Khóa YKK',
    images: [img('messenger-paddock-1'), img('messenger-paddock-2')],
    category: 'phu-kien', subCategory: 'tui-xach',
    tags: ['f1', 'accessories', 'premium', 'tech'],
    basePrice: 899000, material: 'Ballistic Nylon 1680D',
    variants: variants(OS, [BLACK, NAVY]),
    rating: { average: 4.8, count: 134 }, soldCount: 450, isFeatured: false, isActive: true,
  },
  {
    name: 'Túi Waist Bag BoBo Circuit',
    slug: 'tui-waist-bag-bobo-circuit',
    description: 'Túi bao tử nylon nhẹ, đeo hông hoặc chéo ngực, khoá zip kép chống trộm.',
    shortDescription: 'Nylon nhẹ | Đeo hông/chéo | Zip kép',
    images: [img('waist-bag-circuit-1'), img('waist-bag-circuit-2')],
    category: 'phu-kien', subCategory: 'tui-bao-tu',
    tags: ['f1', 'accessories', 'casual', 'new-arrival'],
    basePrice: 349000, material: 'Nylon Ripstop 100%',
    variants: variants(OS, [BLACK, RED, ORANGE]),
    rating: { average: 4.8, count: 389 }, soldCount: 1580, isFeatured: true, isActive: true,
  },
  {
    name: 'Kính Mắt BoBo Racer Aviator',
    slug: 'kinh-mat-bobo-racer-aviator',
    description: 'Kính aviator gọng kim loại mạ chrome, tròng phân cực UV400. Phong cách F1 driver cổ điển.',
    shortDescription: 'Aviator chrome | Phân cực UV400 | F1 classic',
    images: [img('aviator-sunglasses-1'), img('aviator-sunglasses-2')],
    category: 'phu-kien', subCategory: 'kinh-mat',
    tags: ['f1', 'accessories', 'premium'],
    basePrice: 599000, material: 'Metal frame, Polycarbonate lens',
    variants: variants(OS, [SILVER, BLACK]),
    rating: { average: 4.7, count: 234 }, soldCount: 840, isFeatured: false, isActive: true,
  },
  {
    name: 'Kính Mắt BoBo Wrap Shield',
    slug: 'kinh-mat-bobo-wrap-shield',
    description: 'Shield sunglasses wraparound bảo vệ cả viền mắt, tròng gradient xám, chuẩn vibe đường đua.',
    shortDescription: 'Wraparound | Gradient xám | Race track vibe',
    images: [img('shield-sunglasses-1'), img('shield-sunglasses-2')],
    category: 'phu-kien', subCategory: 'kinh-mat',
    tags: ['f1', 'accessories', 'trending'],
    basePrice: 649000, material: 'TR90 frame, Polycarbonate lens',
    variants: variants(OS, [BLACK, { color: 'Khói', hex: '#708090', skuCode: 'SMK' }]),
    rating: { average: 4.8, count: 312 }, soldCount: 1120, isFeatured: true, isActive: true,
  },
  {
    name: 'Vớ BoBo Racing Stripe Mid Calf',
    slug: 'vo-bobo-racing-stripe-mid-calf',
    description: 'Bộ 3 đôi vớ cotton dài mid-calf, kẻ sọc màu đua phối nhiều màu. Elastic ôm chân.',
    shortDescription: 'Bộ 3 đôi | Mid-calf | Kẻ sọc màu đua',
    images: [img('racing-socks-stripe-1')],
    category: 'phu-kien', subCategory: 'vo',
    tags: ['f1', 'accessories', 'casual'],
    basePrice: 199000, material: 'Cotton 80%, Polyester 15%, Spandex 5%',
    variants: variants(OS, [RED, BLUE, ORANGE]),
    rating: { average: 4.6, count: 445 }, soldCount: 1980, isFeatured: false, isActive: true,
  },
  {
    name: 'Vớ BoBo No-Show Carbon',
    slug: 'vo-bobo-no-show-carbon',
    description: 'Bộ 5 đôi vớ cổ thấp no-show, đế silicon chống trượt, chất cotton mềm dịu.',
    shortDescription: 'No-show | Silicon chống trượt | Bộ 5 đôi',
    images: [img('noshow-socks-carbon-1')],
    category: 'phu-kien', subCategory: 'vo',
    tags: ['accessories', 'casual', 'basic'],
    basePrice: 249000, material: 'Cotton 85%, Polyester 10%, Spandex 5%',
    variants: variants(OS, [BLACK, WHITE, GRAY]),
    rating: { average: 4.7, count: 567 }, soldCount: 2560, isFeatured: false, isActive: true,
  },
  {
    name: 'Găng Tay BoBo Driving Gloves',
    slug: 'gang-tay-bobo-driving-gloves',
    description: 'Găng tay lái xe da thật hở ngón, thêu logo BoBo mu bàn tay, cổ tay snap button.',
    shortDescription: 'Da thật hở ngón | Thêu logo | Snap button',
    images: [img('driving-gloves-1'), img('driving-gloves-2')],
    category: 'phu-kien', subCategory: 'gang-tay',
    tags: ['f1', 'accessories', 'premium', 'driver'],
    basePrice: 799000, material: 'Genuine Leather',
    careInstructions: ['Lau nhẹ bằng khăn mềm', 'Không giặt nước'],
    variants: variants(OS, [BLACK, { color: 'Nâu Da Bò', hex: '#8B4513', skuCode: 'TAN' }]),
    rating: { average: 4.8, count: 89 }, soldCount: 290, isFeatured: false, isActive: true,
  },
  {
    name: 'Khăn Choàng BoBo Racing Check',
    slug: 'khan-choang-bobo-racing-check',
    description: 'Khăn lụa nhân tạo họa tiết kẻ ca rô racing đen trắng, 90x90cm, đa năng buộc cổ, đầu hoặc túi.',
    shortDescription: 'Lụa nhân tạo | Ca rô racing | Đa năng',
    images: [img('scarf-racing-check-1')],
    category: 'phu-kien', subCategory: 'khan-choang',
    tags: ['f1', 'accessories', 'elegant'],
    basePrice: 349000, material: 'Satin Polyester 100%',
    variants: variants(OS, [{ color: 'Đen - Trắng', hex: '#000000', skuCode: 'BNW' }, RED]),
    rating: { average: 4.6, count: 134 }, soldCount: 480, isFeatured: false, isActive: true,
  },
  {
    name: 'Ví BoBo Racing Bifold',
    slug: 'vi-bobo-racing-bifold',
    description: 'Ví da PU gập đôi, in hoạ tiết carbon vân tinh tế, ngăn 6 thẻ + ngăn tiền mặt.',
    shortDescription: 'PU carbon vân | 6 ngăn thẻ | Gập đôi',
    images: [img('bifold-wallet-racing-1')],
    category: 'phu-kien', subCategory: 'vi',
    tags: ['f1', 'accessories', 'premium'],
    basePrice: 449000, material: 'PU Leather cao cấp',
    variants: variants(OS, [BLACK, CARBON]),
    rating: { average: 4.7, count: 267 }, soldCount: 980, isFeatured: false, isActive: true,
  },
  {
    name: 'Ví Cầm Tay BoBo Paddock Clutch',
    slug: 'vi-cam-tay-bobo-paddock-clutch',
    description: 'Clutch nhỏ gọn da PU nhẵn với logo BoBo khắc nổi, khóa từ tính. Phụ nữ paddock.',
    shortDescription: 'Da PU nhẵn | Logo khắc | Khóa từ tính',
    images: [img('clutch-paddock-1')],
    category: 'phu-kien', subCategory: 'vi',
    tags: ['f1', 'women', 'accessories', 'elegant'],
    basePrice: 399000, material: 'PU Leather',
    variants: variants(OS, [BLACK, RED, SILVER]),
    rating: { average: 4.7, count: 156 }, soldCount: 540, isFeatured: false, isActive: true,
  },
  {
    name: 'Vòng Cổ BoBo Pit Lane Chain',
    slug: 'vong-co-bobo-pit-lane-chain',
    description: 'Dây chuyền thép không gỉ mạ bạc, mặt charm hình bánh lái F1 nhỏ. Unisex.',
    shortDescription: 'Thép mạ bạc | Charm bánh lái | Unisex',
    images: [img('necklace-pitlane-1')],
    category: 'phu-kien', subCategory: 'trang-suc',
    tags: ['f1', 'accessories', 'jewelry'],
    basePrice: 299000, material: 'Stainless Steel 316L',
    variants: variants(OS, [SILVER, BLACK]),
    rating: { average: 4.7, count: 312 }, soldCount: 1240, isFeatured: false, isActive: true,
  },
  {
    name: 'Vòng Tay BoBo Racing Bracelet',
    slug: 'vong-tay-bobo-racing-bracelet',
    description: 'Vòng tay cao su lưu hóa đen với phù điêu số racing màu đỏ. Ngầu, đơn giản.',
    shortDescription: 'Cao su lưu hóa | Phù điêu số | Bold',
    images: [img('bracelet-racing-1')],
    category: 'phu-kien', subCategory: 'trang-suc',
    tags: ['f1', 'accessories', 'casual'],
    basePrice: 149000, material: 'Vulcanized Rubber',
    variants: variants(OS, [BLACK, RED]),
    rating: { average: 4.5, count: 234 }, soldCount: 920, isFeatured: false, isActive: true,
  },
  {
    name: 'Ghim Cài Áo BoBo Racing Enamel',
    slug: 'ghim-cai-ao-bobo-racing-enamel',
    description: 'Ghim enamel set 3 chiếc: mũ bảo hiểm, cờ ca rô, bánh lái. Trang trí túi, áo khoác.',
    shortDescription: 'Set 3 enamel pins | Mũ + Cờ + Bánh lái | Trang trí',
    images: [img('enamel-pin-racing-1')],
    category: 'phu-kien', subCategory: 'ghim-cai',
    tags: ['f1', 'accessories', 'collectible'],
    basePrice: 199000, material: 'Zinc alloy, Soft enamel',
    variants: variants(OS, [{ color: 'Multi', hex: '#FF0000', skuCode: 'MLT' }]),
    rating: { average: 4.9, count: 489 }, soldCount: 2100, isFeatured: false, isActive: true,
  },
  {
    name: 'Lô Tô BoBo Sticker Pack F1',
    slug: 'lo-to-bobo-sticker-pack-f1',
    description: 'Bộ 12 sticker vinyl chống nước dán mũ bảo hiểm, laptop. Logo đội đua, cờ, số xe.',
    shortDescription: 'Vinyl chống nước | 12 stickers | Dán đa năng',
    images: [img('sticker-pack-f1-1')],
    category: 'phu-kien', subCategory: 'sticker',
    tags: ['f1', 'accessories', 'fun', 'collectible'],
    basePrice: 99000, material: 'Vinyl cao cấp chống nước',
    variants: variants(OS, [{ color: 'Multi Color', hex: '#FF0000', skuCode: 'CLR' }]),
    rating: { average: 4.8, count: 678 }, soldCount: 3400, isFeatured: false, isActive: true,
  },
  {
    name: 'Mũ Lưỡi Trai BoBo F1 Embroidered',
    slug: 'mu-luoi-trai-bobo-f1-embroidered',
    description: 'Mũ lưỡi trai 5-panel với thêu 3D hình chiếc xe đua chạy trên mặt trước. Chất liệu twill bền.',
    shortDescription: '5-panel twill | Thêu 3D xe đua | Bền đẹp',
    images: [img('cap-f1-embroidered-1'), img('cap-f1-embroidered-2')],
    category: 'phu-kien', subCategory: 'mu',
    tags: ['f1', 'accessories', 'new-arrival', 'best-seller'],
    basePrice: 329000, material: 'Cotton Twill 100%',
    variants: variants(OS, [BLACK, RED, NAVY, WHITE]),
    rating: { average: 4.9, count: 512 }, soldCount: 2340, isFeatured: true, isActive: true,
  },
  {
    name: 'Túi Backpack BoBo Race Day',
    slug: 'tui-backpack-bobo-race-day',
    description: 'Ba lô 20L vải nylon kháng nước, ngăn laptop 15", phản quang bên hông, phong cách race day.',
    shortDescription: '20L kháng nước | Ngăn laptop 15" | Phản quang',
    images: [img('backpack-raceday-1'), img('backpack-raceday-2')],
    category: 'phu-kien', subCategory: 'ba-lo',
    tags: ['f1', 'accessories', 'premium', 'tech'],
    basePrice: 1190000, material: 'Nylon 900D kháng nước',
    variants: variants(OS, [BLACK, NAVY]),
    rating: { average: 4.8, count: 223 }, soldCount: 780, isFeatured: true, isActive: true,
  },
  {
    name: 'Thắt Lưng BoBo Racing Harness',
    slug: 'that-lung-bobo-racing-harness',
    description: 'Dây đai kiểu harness lấy cảm hứng từ harness dây an toàn F1, phối vest hay áo thun đều nổi.',
    shortDescription: 'Harness F1 inspired | Phối áo | Bắt mắt',
    images: [img('harness-racing-1')],
    category: 'phu-kien', subCategory: 'day-lung',
    tags: ['f1', 'accessories', 'fashion', 'bold'],
    basePrice: 499000, material: 'Nylon Webbing cao cấp',
    variants: variants(OS, [BLACK, RED]),
    rating: { average: 4.7, count: 178 }, soldCount: 590, isFeatured: false, isActive: true,
  },
  {
    name: 'Mũ Helmet-Style BoBo F1 Cap',
    slug: 'mu-helmet-style-bobo-f1-cap',
    description: 'Mũ phong cách nón bảo hiểm F1 mini, kết cấu foam cứng nhẹ, lỗ thông khí bên thái dương.',
    shortDescription: 'Helmet style | Foam cứng nhẹ | Thông khí',
    images: [img('helmet-cap-f1-1'), img('helmet-cap-f1-2')],
    category: 'phu-kien', subCategory: 'mu',
    tags: ['f1', 'accessories', 'bold', 'statement'],
    basePrice: 459000, material: 'EPS Foam + PU Shell',
    variants: variants(OS, [RED, BLACK, BLUE, ORANGE]),
    rating: { average: 4.8, count: 312 }, soldCount: 1120, isFeatured: true, isActive: true,
  },
  {
    name: 'Móc Khóa BoBo Racing Wheel',
    slug: 'moc-khoa-bobo-racing-wheel',
    description: 'Móc khóa hình bánh xe F1 bằng kẽm mạ bạc, logo BoBo mặt sau. Quà tặng racing fan.',
    shortDescription: 'Bánh xe F1 | Kẽm mạ bạc | Quà tặng',
    images: [img('keychain-racing-wheel-1')],
    category: 'phu-kien', subCategory: 'moc-khoa',
    tags: ['f1', 'accessories', 'gift'],
    basePrice: 149000, material: 'Zinc alloy mạ bạc',
    variants: variants(OS, [SILVER, BLACK]),
    rating: { average: 4.6, count: 389 }, soldCount: 1780, isFeatured: false, isActive: true,
  },
  {
    name: 'Túi Shoulder BoBo Paddock Lady',
    slug: 'tui-shoulder-bobo-paddock-lady',
    description: 'Túi đeo vai da PU nắp gập, chuỗi xích kim loại, logo BoBo khắc nổi. Nhỏ gọn, thanh lịch.',
    shortDescription: 'Da PU nắp gập | Chain xích | Thanh lịch',
    images: [img('shoulder-bag-paddock-lady-1'), img('shoulder-bag-paddock-lady-2')],
    category: 'phu-kien', subCategory: 'tui-xach',
    tags: ['f1', 'women', 'accessories', 'premium'],
    basePrice: 749000, material: 'PU Leather cao cấp, Metal chain',
    variants: variants(OS, [BLACK, RED, SILVER]),
    rating: { average: 4.8, count: 178 }, soldCount: 620, isFeatured: false, isActive: true,
  },
  {
    name: 'Bình Giữ Nhiệt BoBo Racing Thermos',
    slug: 'binh-giu-nhiet-bobo-racing-thermos',
    description: 'Bình giữ nhiệt 500ml thép không gỉ, in tên BoBo + số xe dạng racing livery. Giữ lạnh 24h.',
    shortDescription: 'Thép 500ml | Racing livery | Giữ lạnh 24h',
    images: [img('thermos-racing-bobo-1')],
    category: 'phu-kien', subCategory: 'binh-nuoc',
    tags: ['f1', 'accessories', 'lifestyle', 'gift'],
    basePrice: 399000, material: 'Stainless Steel 304',
    variants: variants(OS, [BLACK, RED, SILVER]),
    rating: { average: 4.8, count: 312 }, soldCount: 1240, isFeatured: false, isActive: true,
  },
  {
    name: 'Ví Card Holder BoBo F1 Slim',
    slug: 'vi-card-holder-bobo-f1-slim',
    description: 'Card holder siêu mỏng da PU vân carbon, giữ được 6-8 thẻ và tiền mặt. Gọn nhẹ tối giản.',
    shortDescription: 'Siêu mỏng | 6–8 thẻ | Vân carbon PU',
    images: [img('card-holder-f1-slim-1')],
    category: 'phu-kien', subCategory: 'vi',
    tags: ['f1', 'accessories', 'minimal', 'premium'],
    basePrice: 299000, material: 'PU Leather vân carbon',
    variants: variants(OS, [BLACK, CARBON, RED]),
    rating: { average: 4.7, count: 245 }, soldCount: 890, isFeatured: false, isActive: true,
  },
  {
    name: 'Băng Đầu BoBo Racing Headband',
    slug: 'bang-dau-bobo-racing-headband',
    description: 'Băng đầu terry vải cotton thấm hút tốt, logo BoBo thêu mặt trước. Tập gym hoặc phối outfit.',
    shortDescription: 'Terry cotton | Thấm hút | Đa năng',
    images: [img('headband-racing-bobo-1')],
    category: 'phu-kien', subCategory: 'phu-kien-toc',
    tags: ['f1', 'accessories', 'sport', 'casual'],
    basePrice: 149000, material: 'Cotton Terry 100%',
    variants: variants(OS, [BLACK, WHITE, RED, NAVY]),
    rating: { average: 4.6, count: 312 }, soldCount: 1340, isFeatured: false, isActive: true,
  },
];

// ---------------------------------------------------------------------------
// Seed runner
// ---------------------------------------------------------------------------
const seedData = async () => {
  try {
    await connectDB();

    const destroyFlag = process.argv.includes('--destroy');
    if (destroyFlag) {
      await require('../models/Product').deleteMany({});
      console.log('🗑️  Đã xóa tất cả sản phẩm');
      process.exit(0);
    }

    await require('../models/Product').deleteMany({});
    await require('../models/Product').insertMany(sampleProducts);

    console.log(`✅ Đã seed ${sampleProducts.length} sản phẩm mẫu thành công!`);
    console.log(`📦 Danh mục:`);
    const cats = {};
    sampleProducts.forEach(p => { cats[p.category] = (cats[p.category] || 0) + 1; });
    Object.entries(cats).forEach(([cat, n]) => console.log(`   ${cat}: ${n} sản phẩm`));

    process.exit(0);
  } catch (error) {
    console.error('❌ Seed thất bại:', error);
    process.exit(1);
  }
};

seedData();
